models:
  "nomic-ai/nomic-embed-text-v1.5":
    prefix_query: "search_query: "
    prefix_document: "search_document: "
    dimension: 768
    
  "Xenova/all-MiniLM-L12-v2":
    prefix_query: ""
    prefix_document: ""
    dimension: 384

  "Xenova/all-MiniLM-L6-v2":
    prefix_query: ""
    prefix_document: ""
    dimension: 384

  "Xenova/multi-qa-MiniLM-L6-cos-v1":
    prefix_query: ""
    prefix_document: ""
    dimension: 384

  "Xenova/multi-qa-distilbert-cos-v1":
    prefix_query: ""
    prefix_document: ""
    dimension: 768


  "Xenova/all-mpnet-base-v2":
    prefix_query: ""
    prefix_document: ""
    dimension: 768

  "Xenova/paraphrase-mpnet-base-v2":
    prefix_query: ""
    prefix_document: ""
    dimension: 768

  
  "Xenova/paraphrase-multilingual-MiniLM-L12-v2":
    prefix_query: ""
    prefix_document: ""
    dimension: 384



